# metadata -- add as many key/value pairs as you want
[metadata]
event = "Helsinki-2019"

[settings]
# replace the context name below with your DCN cluster context
# Tip: you can find your context by running: kubectl config get-contexts
kubeContext = "YOUR-KUBE_CONTEXT-HERE"

# define your k8s namespaces. If they don't exist, helmsman will attempt to create them
# syntax: environment_name = "k8s_namespace"
[namespaces]
# replace userX below with your namespace name
[namespaces.userX]
   useTiller = true
[namespaces.kube-system]
   installTiller = false

# define any private/public helm charts repos you would like to get charts from
# syntax: repo_name = "repo_url"
[helmRepos]
stable = "https://kubernetes-charts.storage.googleapis.com"
incubator = "http://storage.googleapis.com/kubernetes-charts-incubator"

# define the desired state of your k8s applications (helm charts)

[apps]

[apps.tomcat-prod]
namespace = "userX" # maps to the namespace as defined in namespaces above
enabled = true # change to false if you want to delete this release [default is flase]
chart = "stable/tomcat" # chart name (repo/chart)
version = "0.4.0" # chart version

[apps.tomcat-test]
namespace = "userX" # maps to the namespace as defined in namespaces above
enabled = true # change to false if you want to delete this release [default is flase]
chart = "stable/tomcat" # chart name (repo/chart)
version = "0.4.0" # chart version
