# metadata -- add as many key/value pairs as you want
[metadata]
event = "DCN-Oslo2018"

[settings]
# replace the context name below with your DCN cluster context
# Tip: you can find your context by running: kubectl config get-contexts
kubeContext = "gke_praqma-education_europe-west1-b_dcn-cluster-3"

# define your k8s namespaces. If they don't exist, helmsman will attempt to create them
# syntax: environment_name = "k8s_namespace"
[namespaces]
[namespaces.default]
[namespaces.playground]

# define any private/public helm charts repos you would like to get charts from
# syntax: repo_name = "repo_url"
[helmRepos]
stable = "https://kubernetes-charts.storage.googleapis.com"
incubator = "http://storage.googleapis.com/kubernetes-charts-incubator"
local = "http://127.0.0.1:8879/charts"

# define the desired state of your k8s applications (helm charts)

[apps]

[apps.kubernetes-dashboard]
name = "kubernetes-dashboard" # should be unique across all apps
description = "stable/kubernetes-dashboard"
namespace = "default" # maps to the namespace as defined in namespaces above
enabled = true # change to false if you want to delete this release [default is flase]
chart = "stable/kubernetes" # chart name (repo/chart)
version = "0.4.4" # chart version
valuesFile = "k8s-dashboard-values.yaml"  # leaving it empty uses the default chart values
purge = false # will only be considered when there is a delete operation

[apps.helm-echoserver]
name = "echoserver" # should be unique across all apps
description = ""
namespace = "playground" # maps to the namespace as defined in namespaces above
enabled = true # change to false if you want to delete this release [default is flase]
chart = "local/helm-echoserver" # chart name (repo/chart)
version = "0.1.0" # chart version
valuesFile = ""  # leaving it empty uses the default chart values
purge = false # will only be considered when there is a delete operation
