# metadata -- add as many key/value pairs as you want
[metadata]
event = "DCN-Oslo2018"

[certificates]
caCrt = "gs://cluster-keys/keys/ca.crt" 
caKey = "gs://cluster-keys/keys/client_key.key"
caClient = "gs://cluster-keys/keys/client_certificate.crt"

[settings]
kubeContext = "demo-cluster"
username = "admin"
password = "$K8S_PASSWORD" # the name of an environment variable containing the k8s password
clusterURI = "$K8S_URI" # cluster API
serviceAccount = "tiller"


# define your k8s namespaces. If they don't exist, helmsman will attempt to create them
# syntax: [namespaces.<namespace_name>]
[namespaces]

[namespaces.dev]
installTiller = true
tillerServiceAccount = "dev-tiller"

[namespaces.test]
installTiller = true
tillerServiceAccount = "test-tiller"

[namespaces.prod]
protected = true
installTiller = true
tillerServiceAccount = "prod-tiller"
caCert = "gs://helm-tls/ca.cert.pem"
tillerCert = "gs://helm-tls/tiller.cert.pem"
tillerKey = "gs://helm-tls/tiller.key.pem"
clientCert = "gs://helm-tls/client.cert.pem"
clientKey = "gs://helm-tls/client.key.pem"

# define any private/public helm charts repos you would like to get charts from
# syntax: repo_name = "repo_url"
[helmRepos]
stable = "https://kubernetes-charts.storage.googleapis.com"
incubator = "http://storage.googleapis.com/kubernetes-charts-incubator"
pantel = "https://pantel-tests-charts.storage.googleapis.com/"


[apps]

[apps.helm-echoserver]
name = "echoserver" # should be unique across all apps
description = "Pantel echoserver app."
namespace = "dev" # maps to the namespace as defined in namespaces above
enabled = true # change to false if you want to delete this release [default is flase]
chart = "pantel/echoserver" # chart name (repo/chart)
version = "0.1.0" # chart version
valuesFile = ""  # leaving it empty uses the default chart values
protected = true

[apps.wordpress]
name = "wordpress" # should be unique across all apps
description = "Wordpress CMS"
namespace = "prod" # maps to the namespace as defined in namespaces above
enabled = true # change to false if you want to delete this release [default is flase]
chart = "stable/wordpress" # chart name (repo/chart)
version = "2.1.0" # chart version
valuesFile = ""  # leaving it empty uses the default chart values
